wiki/encyclopedia/urls.py
from django.urls import path

from . import views


app_name="encyclopedia"
urlpatterns = [
    path("wiki/", views.index, name="index"),
    path("wiki/create_page", views.create_page, name="create_page"),
    path("wiki/random_page", views.random_page, name="random_page"),
    path("wiki/search_page", views.search_page, name="search_page"),
    path("wiki/about", views.about, name="about"),
    path("wiki/<slug:title>", views.visit_entry, name="visit_entry"),
    path("wiki/edit/<str:pageName>", views.edit, name="edit"),
   
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    # path('summernote/', include('django_summernote.urls')),
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from django import forms


class CreatForm(forms.Form):
    """
    This form allows the user to create a new article in the wiki.    
    """ 
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea)
  
class EditForm(forms.Form):
    """
    This form allows the user to update an existing article. 
    The user can update the content of the article but not the title.
    """ 
    title = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    content = forms.CharField(widget=forms.Textarea)

wiki/encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import random
from . import util
from markdown2 import Markdown
from .forms import CreatForm, EditForm

def index(request):
    """
    Lists all entries in the encyclopedia.
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def visit_entry(request, title):
    """
    Goes to the specific entry details.
    """
    return render(request,"encyclopedia/visit_entry.html",{
        "entry": util.get_entry(title),
        "title": title
    })


def create_page(request):
    """
    Shows a form that allows the user to create a new encyclopedia entry.
    """
    entries=util.list_entries()
    if request.method == "POST":
        form = CreatForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            title = form.cleaned_data["title"]
            
            for entry in entries:
                if title == entry:
                    return render(request,"encyclopedia/create_page.html",{
                        "form": form,
                        "isexist": True,
                        "message": "This Title already exist."
                    })
                else:
                    util.save_entry(title, content)
                    return HttpResponseRedirect(reverse("encyclopedia:index"))
        
        else:
            return render(request,"encyclopedia/create_page.html",{
                "form": form
            })
    return render(request, "encyclopedia/create_page.html",{
        "form": CreatForm()
    } )


def random_page(request):
    """
    Picks a random article from the encyclopedia and shows it to the user.
    """
    entries = util.list_entries()
    title = random.choice(entries)
    return render(request,"encyclopedia/visit_entry.html",{
        "entry": util.get_entry(title),
        "title": title
    })


def search_page(request):
    """
    - If the user write the correct name of the article in the search form, he will
        be taken to the content of this article.
    - Otherwise, a list of all the entries' name that match the query string will
        be shown.  
    """
    if request.method ==  "GET":
        page = request.GET.get('q')
        entries = util.list_entries()
        entries_set=set(entries)

        if page in entries_set:
            return render(request, "encyclopedia/visit_entry.html",{
                "entry": util.get_entry(page),
                "title": page
            })
        
        else:
            results = list(filter(lambda x: page in x, entries))
            return render(request, "encyclopedia/search_page.html",{
                "results": results
            })

        

def edit(request, pageName):
    """
    Shows a form that allows the user to edit the content of selected article.
    """
    
    if request.method == "POST":
        form = EditForm(request.POST)
    
        if form.is_valid():    
            content = form.cleaned_data["content"]
            title = form.cleaned_data["title"]
            
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:visit_entry", args=(title, )))
                    
        else:

            form = EditForm({'title': pageName, 'content': util.get_entry(pageName) })
            return render(request, "encyclopedia/edit_page.html", {
                "form": EditForm(),
                "pageName": pageName
            })
    
    
    return render(request, "encyclopedia/edit_page.html", {
        "form":  EditForm({'title': pageName, 'content': util.get_entry(pageName) }),
        "pageName": pageName
    })

def about(request):
    """
    Shows information about the project.
    """
    return render(request,"encyclopedia/about.html")

wiki/encyclopedia/templates/encyclopedia/about.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    About
{% endblock %}

{% block body %}
    <h1>About This Project:</h1><br/>
    <p> This Wiki project is an implementation of the assignment of
        CS50’s Web Programming with Python and JavaScript course introduced by Harvard univesity.
        For more information please see:
        <a href="https://cs50.harvard.edu/web/2020/projects/1/wiki/">Wiki Project</a>
     </p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% load crispy_forms_tags %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

    <form action="{% url 'encyclopedia:create_page' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Submit">
        <a href="{% url 'encyclopedia:index' %}" style="float: right;">See your entry</a>
    </form>

    {% if isexist %}
        {{message}}
    {% endif %}

   

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% load crispy_forms_tags %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
    
    <form action="{% url 'encyclopedia:edit' pageName %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Save">
        <a href="{% url 'encyclopedia:visit_entry' pageName %}" style="float:right">See your entry</a>

    </form>
   

    {% if isexist %}

        {{message}}
            
    {% endif %}

    
       
    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>Encyclopedia Articles</h1>
<hr class="my-4">

<ul>
    {% for entry in entries %}
        <li>
            <a href="{% url 'encyclopedia:visit_entry' entry %}"> {{ entry }} </a>
        </li>
    {% endfor %}

</ul>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body style="padding-top: 56px;">
    <!--  for toggle button functionality when screen size getting samller -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Wiki</a>
        <!-- navbar collapse when you switch to the small devices -->
        <div class="collapse navbar-collapse flex-row-reverse" id="navbar">

            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'encyclopedia:index' %} ">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'encyclopedia:create_page' %}">Create New Article <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'encyclopedia:random_page' %}">Random Article</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'encyclopedia:about' %}">About</a>
                </li>
            </ul>
            <!-- form-inline and form-control are style the search form -->
            <form class="form-inline" action="{% url 'encyclopedia:search_page' %}" method="GET">
                <input type="text" name="q" placeholder="Search..." class="form-control">
            </form>
        </div>
        {% block navbar %}
        {% endblock navbar %}
    </nav>
    <!-- Main content start here -->
    <div id="main-container" class="container-fluid">
        <div class="row">
            <!-- to hide the side bar in extra small devices d-none and d-sm-block -->
            <div class="col-sm-3 col-md-2 col-lg-2 d-none d-sm-block sidebar">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search_page' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">Create New Article</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}"> Random Article </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:about' %}"> About </a>
                </div>

                {% block nav %}
                {% endblock %}
            </div>

            <div class="main-content-container col-sm-9 col-md-10 col-lg-10 ">
                <div class="col-6 col-md-4"></div>
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

    <!-- This for rendering markdown files .md to html format -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.1/marked.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".content-markdown").each(function () {
                var content = $(this).text()
                // console.log(content)
                var markedContent = marked(content)
                // console.log(markedContent)
                $(this).html(markedContent)
            })
        })

        // This function to activate the current link
        $(document).ready(function () {
            var url = window.location;
             // Will only work if string in href matches with location
            $('ul.nav a[href="' + url + '"]').parent().addClass('active');

            // Will also work for relative and absolute hrefs
            $('ul.nav a').filter(function () {
                return this.href == url;
             }).parent().addClass('active').parent().parent().addClass('active');
    });
    </script>
</body>

</html>

wiki/encyclopedia/templates/encyclopedia/random_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
   
    <div class="content-markdown">

        {{ entry }}

    </div>    
   
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1> Found Pages</h1>

<ul>
    {% for item in results %}
        <li>
            <a href="{% url 'encyclopedia:visit_entry' item %}"> {{ item }} </a>
        </li>
    {% endfor %}

</ul>

{% if not results%}
    <p>0 results found</p>

{%  endif %}
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/visit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
   
    <div class="content-markdown">
        {{ entry| safe }}
    </div>  

    
        <a href="{% url 'encyclopedia:edit' title %}">Edit Page</a> 
    

{% endblock %}